# Generated by Django 5.0.1 on 2024-01-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFolder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
